# Generated by Django 4.2 on 2024-11-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_option_options_option_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
            preserve_default=False,
        ),
    ]
